### ISSUE TITLE
Broken with build 23430

### ISSUE THREAD

**Issue by MrAndy42** [qhgz2013/dsp_save_parser#4]
Traceback (most recent call last):
  File "D:\source\dsp_save_parser-master\resources.py", line 26, in <module>
    data = s.GameSave.parse(f)
           ^^^^^^^^^^^^^^^^^^^
  File "D:\source\dsp_save_parser-master\dsp_save_parser\generated.py", line 215, in parse
    game_data = GameData.parse(stream)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\source\dsp_save_parser-master\dsp_save_parser\generated.py", line 418, in parse
    preferences = GamePrefsData.parse(stream)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\source\dsp_save_parser-master\dsp_save_parser\generated.py", line 1025, in parse
    assert version == 13
           ^^^^^^^^^^^^^
[gameSaveFile.zip](https://github.com/user-attachments/files/17802584/gameSaveFile.zip)

**Comment by MrAndy42** [comment]
Thanks for the quick turnaround!
